name: linkcordsapplication
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  youtube_player_flutter: ^9.1.1
  avatar_glow: ^3.0.1
  provider: ^6.1.2
  line_icons: ^2.0.3
  nb_utils: ^7.0.7
  firebase_storage: ^13.0.1
  url_launcher: ^6.3.1
  ikchatbot: ^1.0.5
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  http: ^1.4.0
  path: ^1.8.3
  fluttertoast: ^8.2.1 # (Use the latest stable version compatible with your Flutter version)
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  page_transition: ^2.1.0
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  show_custom_snackbar: ^0.0.1
  shared_preferences: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/Animation - 1731750840361.json
    - assets/GemePageSplach.json
    - assets/loading.gif